M48
; DRILL file {KiCad 8.0.6} date 2025-07-03T11:32:33-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-03T11:32:33-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X99.0Y-70.5
X99.0Y-109.0
X151.5Y-70.5
X151.5Y-109.0
M30
